site_name: JACoW - Running an ECRIS
#site_url: https://docs-ECRIS.JACoW.org
theme: material
repo_name: 'jacow-org/docs-ECRIS'
repo_url: 'https://github.com/jacow-org/docs-ECRIS'
nav:
  - Introduction: index.md
  - Glossary: glossary.md 
  - Organising Committees: committees.md
  - General instructions:
    - How to login to the Indico event: General/JACoWlogin.md
    - How to submit an abstract: General/submission.md
    - How to edit your abstracts: General/editing.md
    - How to edit your contributions: General/contributions.md
  - Delivery and Initial Setup - Admin:
    - Access to new event: InitialSetup/intro.md
    - Management area: 
      - Settings, Timetable, Protection: InitialSetup/mgmt_area_01.md
      - Organization: InitialSetup/mgmt_area_02.md
      - Workflows: InitialSetup/mgmt_area_03.md
      - Reports: InitialSetup/mgmt_area_04.md
      - Customization: InitialSetup/mgmt_area_05.md
  # - Invited Oral Presentations:
  #   - Introduction: InvitedOrals/intro.md
  #   - Scientific Secretariat/Admin: 
  #     - Intial Setup: InvitedOrals/SSsetup.md
  #     - How submission will work: InvitedOrals/SSsubmission.md
  #     - Call for Proposals for Invited Oral Presentations: InvitedOrals/SScall.md
  #     - Post submission duties: InvitedOrals/SSpostsubmit.md
  #     - Abstract Initial QA: InvitedOrals/SSinitialQA.md
  #     - Setups for the SPC review: InvitedOrals/SSSPCsetup.md
  #     - Creating sessions and assigning programme codes: InvitedOrals/SSpcodes.md
  #     - Publishing the programme: InvitedOrals/SSpublishing.md
  #     - Invitation to invited speakers: InvitedOrals/SSinviteinvited.md
  #     - Tips and tricks: InvitedOrals/SStipsandtricks.md
  #   - SPC/OC/SAB:
  #     - Submission of Proposals for Invited Oral Presentations: InvitedOrals/SABsubmission.md
  #   - SPC - normal workflow:
  #     - "SPC: proposal of track changes": InvitedOrals/SPCtrackreview.md
  #     - "SPC MC Coordinators: review tracks": InvitedOrals/MCCtrackreview.md
  #     - "SPC: give priority to proposals": InvitedOrals/SPCprioritization.md
  #     - "SPC MC Coordinators: accept proposals": InvitedOrals/MCCaccept.md
  #   - SPC - simplified workflow:
  #     - "SPC: review abstracts": InvitedOrals/SPCreview-s.md
  #     - "SPC MC Coordinators: finalise classifications": InvitedOrals/MCCtrackreview.md
  #     - "SPC MC Coordinators: accept proposals": InvitedOrals/MCCaccept.md
  - Contributed Abstracts:
    - Introduction: ContributedAbstracts/intro.md
    - Scientific Secretariat/Admin: 
      - Setup review: ContributedAbstracts/SSsetup.md
      - Post submission duties: ContributedAbstracts/SSpostsubmit.md
  #    - Abstract Initial QA: ContributedAbstracts/SSinitialQA.md
      - Abstract Initial QA: InvitedOrals/SSinitialQA.md
  #    - Setups for the SPC review: ContributedAbstracts/SSSPCsetup.md
      - Setups for the SPC review: InvitedOrals/SSSPCsetup.md
      - Accept Poster presentations: ContributedAbstracts/SSPosters.md
      - Programme codes: ContributedAbstracts/SSpcodes.md
      - Multiple Poster areas: ContributedAbstracts/SSmultipleposterareas.md
    - SPC - normal workflow:
      - "SPC: proposal of track changes": ContributedAbstracts/SPCtrackreview.md
      - "SPC MC Coordinators: review tracks": ContributedAbstracts/MCCtrackreview.md
      - "SPC: give priority to proposals": ContributedAbstracts/SPCprioritization.md
      - "SPC MC Coordinators: accept proposals": ContributedAbstracts/MCCaccept.md
    - SPC - simplified workflow:
      - "SPC: review abstracts": ContributedAbstracts/SPCreview-s.md
      - "SPC MC Coordinators: finalise classifications": ContributedAbstracts/MCCtrackreview-s.md
      - "SPC MC Coordinators: accept proposals": ContributedAbstracts/MCCaccept-s.md
    - "Contributions in multiple sessions": ContributedAbstracts/multiplesessions.md
  - Abstract Booklet:
    - Abstracts booklet with CAT: AbstractBooklet/CAT.md
    - Mail Merge to RTF: AbstractBooklet/MailMerge.md
  - Paper submission:
    # - Light Peer Review:
    #   - Introduction: Paper/LPRintro.md
    #   - LPR module setup: Paper/LPRsetup.md
    #   - Submitting a paper: Paper/LPRSubmit.md
    #   - Communicating with reviewers: Paper/LPRcomm.md
    #   - Submitting the paper for JACoW publication: Paper/LPRSubmit2.md
    #   - Reviewing a paper: Paper/LPRreviewer.md
    #   - Judging a paper: Paper/LPRjudge.md
    - JACoW publication: 
      - Paper editing workflow: Paper/intro.md
      - Submitting a paper: Paper/submit.md
      - Sending comments to editors: Paper/comment.md
      - Uploading new version: Paper/upload.md
      - Approving new version by editor: Paper/approve.md
  - Paper editing:
      - Introduction: Paper/intro.md
      - Editor-in-chief:
        - Setting up: PaperEditing/EIC/setup.md
        - Configuring: PaperEditing/EIC/config.md
        - Editing Team Setup: PaperEditing/EIC/team.md
        - Start Editing: PaperEditing/EIC/open.md
        - Publishing: PaperEditing/EIC/publish.md
      - Editor: 
        - Editables list and assignment: PaperEditing/Editor/assign.md
        - Editing an editable: PaperEditing/Editor/edit.md
        - QA: PaperEditing/Editor/QA.md
      # - Specific ECRIS instructions:
      #   - ECRIS'24: PaperEditing/ECRISs/ECRIS24.md 
  - Proceedings:
    - Introduction: Proceedings/intro.md
    - Paper checks: Proceedings/paperchecks.md
    - Poster checks: Proceedings/posterchecks.md
    - Slides checks: Proceedings/slideschecks.md
    - Authors' list: Proceedings/authorslist.md
    - Final Proceedings: Proceedings/proceedings.md
    - Digital Object Identifiers: Proceedings/doi.md
    - Cleanup: Proceedings/cleanup.md
    - Notes on Proceedigs: Proceedings/notes.md
  - Credits: credits.md
  - FAQ: FAQ.md

